---
version: "3.2"
services:
  portal:
    build:
      context: .
      dockerfile: .pipeline/local.Dockerfile
    image: "wmdevportal:local"
    # Run container as local user to allow Linux mount writes
    user: "${LOCAL_UID:?run `make .env`}:${LOCAL_GID:?run `make .env`}"
    working_dir: /srv/app
    command:
      - bash
      - -c
      - >-
        mkdir -p /tmp/runtime-home &&
        export HOME=/tmp/runtime-home &&
        poetry run mkdocs --verbose build &&
        exec nginx -c /srv/app/contrib/nginx/nginx.conf
    volumes:
      - type: bind
        source: .
        target: /srv/app
        consistency: cached
    ports:
      - "${PORTAL_HTTP_PORT:-9000}:9000"
    restart: always
