site_name: Wikimedia Developer Portal
site_url: https://developer.wikimedia.org/
site_description: Portal for discovering technical documentation about Wikimedia projects
site_author: Wikimedia Foundation and contributors
copyright: Copyright &copy; 2021 Wikimedia Foundation and contributors

nav:
  - Get started: 'index.md'
  - Wikimedia APIs: 'api/index.md'

docs_dir: src
theme:
  name: material
  language: en
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.share

extra_css:
  - assets/stylesheets/theme.css
#extra_javascript:
#  - assets/js/extra.js

extra:
  alternate:
    # Supported content languages. Additional values will be added by our
    # `wikimedia` plugin during build time based on locales found on disk.
    - name: English
      link: /
      lang: en

markdown_extensions:
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search:
      lang: en
  - jinja_wrapper
  - macros:
      module_name: macros
      include_dir: data/includes
      verbose: true
  - translate
