site_name: Wikimedia Developer Portal
site_url: https://developer.wikimedia.org/
site_description: Find technical documentation, and connect with Wikimedia developer communities.
site_author: Wikimedia Foundation and contributors
copyright: Copyright &copy; 2022 Wikimedia Foundation and contributors

nav:
  - Get started:
    - Get started: get-started/index.md
    - Learn about Wikimedia technology: get-started/wikimedia-tech.md
    - Understand the development process: get-started/new-dev.md
    - Learn with tutorials: get-started/tutorials.md
    - Browse by programming language: get-started/browse-languages.md
  - Use content and data:
    - Use content and data: use-content/index.md
    - Explore featured apps: use-content/featured-apps.md
    - Learn with tutorials: use-content/tutorials.md
    - Use wiki content: use-content/content.md
    - Access open data: use-content/data.md
  - Tools and bots:
    - Tools and bots: build-tools/index.md
    - Discover and share tools: build-tools/search.md
    - Get started: build-tools/get-started.md
    - Learn with tutorials: build-tools/tutorials.md
    - Use APIs and data sources: build-tools/apis.md
    - Host tools on Wikimedia servers: build-tools/host-tools.md
  - Contribute:
    - Contribute to Wikimedia open source: contribute/index.md
    - Learn how contributing works: contribute/overview.md
    - Contribute by topic: contribute/by-topic.md
    - Contribute by programming language: contribute/by-language.md
    - Search all projects: contribute/search.md
  - Community:
    - Community: community/index.md
    - Explore hackathons and events: community/events.md
    - Communicate with the tech community: community/communicate.md
    - Learn and share technical skills: community/grow.md
    - Get tech project updates: community/updates.md
    - Learn about Wikimedia technical operations: community/tech-ops.md
  - Get help:
    - Get help: get-help/index.md
    - About: get-help/about.md

docs_dir: src
theme:
  name: material
  custom_dir: data/theme
  language: en
  font: false
  logo: assets/wikimedia.svg
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.share
    - navigation.indexes
    - toc.integrate
    # navigation.instant # breaks cross-language navigation

extra_css:
  - assets/stylesheets/theme.css
#extra_javascript:
#  - assets/js/extra.js

extra:
  homepage: /
  alternate:
    # Supported content languages. Additional values will be added by our
    # `wikimedia` plugin during build time based on locales found on disk.
    - name: English
      link: /
      lang: en
  generator: false
  footer_links:
    - label: Privacy policy
      href: https://foundation.wikimedia.org/wiki/Special:MyLanguage/Privacy_policy
    - label: Terms of Use
      href: https://foundation.wikimedia.org/wiki/Special:MyLanguage/Terms_of_Use
    - label: "Code: GPL-3.0-or-later"
      href: https://www.gnu.org/licenses/gpl-3.0.html
    - label: "Content: CC-BY-SA-3.0"
      href: https://creativecommons.org/licenses/by-sa/3.0/

markdown_extensions:
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search:
      lang: en
  - jinja_wrapper
  - macros:
      module_name: macros
      include_dir: data/includes
      verbose: true
  - translate
