site_name: Wikimedia Developer Portal
site_url: https://developer.wikimedia.org/
site_description: Portal for discovering technical documentation about Wikimedia projects
site_author: Wikimedia Foundation and contributors
copyright: Copyright &copy; 2021 Wikimedia Foundation and contributors

nav:
  - Get started:
    - get-started/index.md
    - get-started/new-dev.md
    - get-started/tutorials.md
    - get-started/wikimedia-tech.md
  - Use content or data:
    - use-content/index.md
    - use-content/apis.md
    - use-content/tutorials.md
    - use-content/content.md
    - use-content/data.md
  - Build tools:
    - build-tools/index.md
    - build-tools/tutorials.md
    - build-tools/apis.md
    - build-tools/host-tools.md
    - build-tools/best-practices.md
  - Contribute:
    - contribute/index.md
    - contribute/overview.md
    - contribute/mediawiki.md
    - contribute/localization.md
    - contribute/documentation.md
    - contribute/accessibility.md
  - Connect and learn:
    - connect-learn/index.md
    - connect-learn/events.md
    - connect-learn/communicate.md
    - connect-learn/grow.md
    - connect-learn/updates.md
  - Get help: get-help/index.md
  - Quick links:
    - quick-links/index.md
    - quick-links/api-catalog.md
    - quick-links/browse-by-api.md
  - About: about/index.md

docs_dir: src
theme:
  name: material
  language: en
  font: false
  logo: assets/wikimedia.svg
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.share
    # navigation.indexes # don't use this if using toc.integrate
    # toc.integrate # don't use this if using navigation.indexes
    # navigation.instant # breaks cross-language navigation

extra_css:
  - assets/stylesheets/theme.css
#extra_javascript:
#  - assets/js/extra.js

extra:
  alternate:
    # Supported content languages. Additional values will be added by our
    # `wikimedia` plugin during build time based on locales found on disk.
    - name: English
      link: /
      lang: en

markdown_extensions:
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

plugins:
  - search:
      lang: en
  - jinja_wrapper
  - macros:
      module_name: macros
      include_dir: data/includes
      verbose: true
  - translate
