pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: lint
        build: lint
        run:
          env: &env-settings
            PIPELINE_RUNNING: '1'

      - name: test
        build: build
        run:
          env: *env-settings

  publish:
    blubberfile: blubber.yaml
    stages:
      - name: production
        build: production
        publish:
          image:
            id: '${.imageID}'
            tags:
              - latest
              - '${setup.tag}'
